### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '{email}' for key 'users_email_unique'

### ISSUE THREAD

**Issue by Underlyingglitch** [FusionApp-Project/FusionApp-Web#12]
If a Discord account is used to login, using the same email as a local user with no connected Discord account, this bug appears.

**Comment by 25huizengek1** [comment]
You should check if the email is already used first before trying to create the Discord-linked account.

**Comment by Underlyingglitch** [comment]
Yes, and then if the user is present -> let them log in to their account first before connecting

**Comment by 25huizengek1** [comment]
I don't know how Eloquent ORM works but I think you should add something like this in `SocialiteController`, before `createOrUpdate`

```php
if (User::query()->where('discord_id', '=', $duser->id)->exists()) return null
```

**Comment by Underlyingglitch** [comment]
Well it can't return null, but yes. Something along the lines of that is needed here
